services:
  db:
    image: postgres:15
    networks:
      - network_fpi
    environment:
      POSTGRES_USER: discorre1
      POSTGRES_PASSWORD: 0412
      POSTGRES_DB: bank
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discorre2 -d bank"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: ./fpibank-system
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://discorre2:0412@db:5432/bank
      SECRET_KEY: eb4ae8f8c330008117d25836b4b27ecd4fefdac5f1492d8101226350c667ff9b
      ALGORITHM: HS256
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    networks:
      - network_fpi
    
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network_fpi
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  frontend:
    build:
      context: ./fpibank-client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./fpibank-client/certs/discorre.ru:/etc/letsencrypt/live/discorre.ru

    networks:
      - network_fpi

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   depends_on:
  #     frontend:
  #       condition: service_started
  #   entrypoint: ["sh", "-c", "sleep 10 && certbot certonly --webroot --webroot-path=/var/www/html --email execute.cpp@gmail.com --agree-tos --no-eff-email -d discorre.ru"]
  #   volumes:
  #     - letsencrypt_data:/etc/letsencrypt
  #     - letsencrypt_logs:/var/log/letsencrypt
  #     - letsencrypt:/var/www/html
  #   networks:
  #     - network_fpi
  #   command: ["sh", "-c", "crond -f && sleep infinity"]
  
  # mitmproxy:
  #     build:
  #       context: ./sniffer
  #     ports:
  #       - "8080:8080"  # Пробрасываем порт на хост
  #     depends_on:
  #       backend:
  #         condition: service_healthy
  #     networks:
  #       - network_fpi

volumes:
  db_data:
  redis_data:
  letsencrypt:
  letsencrypt_data:
  letsencrypt_logs:

networks:
  network_fpi:
    driver: bridge