services:
  db:
    image: postgres:15
    networks:
      - network_fpi
    environment:
      POSTGRES_USER: discorre1
      POSTGRES_PASSWORD: 0412
      POSTGRES_DB: bank
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    # ports:
    #   - "35432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discorre2 -d bank"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: ./fpibank-system
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://discorre2:0412@db:5432/bank
      SECRET_KEY: eb4ae8f8c330008117d25836b4b27ecd4fefdac5f1492d8101226350c667ff9b
      ALGORITHM: HS256
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    networks:
      - network_fpi
    
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network_fpi
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  frontend:
    build:
      context: ./fpibank-client
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_BASE=http://localhost:8000/api/v1

  # mitmproxy:
  #     build:
  #       context: ./sniffer
  #     ports:
  #       - "8080:8080"  # Пробрасываем порт на хост
  #     depends_on:
  #       backend:
  #         condition: service_healthy
  #     networks:
  #       - network_fpi

volumes:
  db_data:
  redis_data:

networks:
  network_fpi:
    driver: bridge